[package]
name = "jit-demo"
version = "0.0.0"
authors = ["The Cretonne Project Developers"]
build = "build.rs"

[[bin]]
name = "toy"
path = "src/toy.rs"

[dependencies]
cretonne = "0.8.0"
cretonne-module = "0.8.0"
cretonne-simplejit = "0.8.0"
peg = "0.5.4"

[build-dependencies]
peg = { version = "0.5.4" }
