[package]
name = "jit-demo"
version = "0.0.0"
authors = ["The Cretonne Project Developers"]
build = "build.rs"

[[bin]]
name = "toy"
path = "src/toy.rs"

[dependencies]
cretonne = { git = "https://github.com/cretonne/cretonne" }
cretonne-module = { git = "https://github.com/cretonne/cretonne" }
cretonne-simplejit = { git = "https://github.com/cretonne/cretonne" }
peg = "0.5.4"

[build-dependencies]
peg = { version = "0.5.4" }
