[package]
name = "jit-demo"
version = "0.0.0"
authors = ["The Cranelift Project Developers"]
build = "build.rs"
license = "Apache-2.0 WITH LLVM-exception"

[[bin]]
name = "toy"
path = "src/toy.rs"

[dependencies]
cranelift = "0.19.0"
cranelift-module = "0.19.0"
cranelift-simplejit = "0.19.0"
peg = "0.5.4"

[build-dependencies]
peg = { version = "0.5.4" }
